CREATE DATABASE IF NOT EXISTS phonebook
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE phonebook;

CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  street VARCHAR(200),
  city VARCHAR(120),
  country VARCHAR(120),
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(200),
  version INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_contacts_phone (phone)
);
